### ISSUE TITLE
inverted color

### ISSUE THREAD

**Issue by GreenFeanor** [birdtechstep/tinydrm#3]
Nice tuto! but the colors are inverted for me. Why?
How to resolve that?

**Comment by birdtechstep** [comment]
> Nice tuto! but the colors are inverted for me. Why?
> How to resolve that?

> Nice tuto! but the colors are inverted for me. Why?
> How to resolve that?

If swap color RGB to BGR 
out_enable:
	switch (mipi->rotation) {
	default:
		addr_mode = ILI9488_MADCTL_MX;
		break;
	case 90:
		addr_mode = ILI9488_MADCTL_MV;
		break;
	case 180:
		addr_mode = ILI9488_MADCTL_MY;
		break;
	case 270:
		addr_mode = ILI9488_MADCTL_MV | ILI9488_MADCTL_MY |
			    ILI9488_MADCTL_MX;
		break;
	}
	//addr_mode |= ILI9488_MADCTL_BGR;
	mipi_dbi_command(mipi, MIPI_DCS_SET_ADDRESS_MODE, addr_mode);
	mipi_dbi_enable_flush(mipi, crtc_state, plane_state);
}

remove //  #line 296
addr_mode |= ILI9488_MADCTL_BGR;

or inverted u can see this
#define ILI9488_CMD_DISP_INVERSION_OFF			0x20
#define ILI9488_CMD_DISP_INVERSION_ON			0x21

add line #275 to
mipi_dbi_command(mipi, ILI9488_CMD_DISP_INVERSION_OFF);
for inversion on or off
